infer:
	python3 deepstream_test_4_usb.py \
		-p /opt/nvidia/deepstream/deepstream-5.1/lib/libnvds_amqp_proto.so \
		-c cfg_amqp.txt \
		-i /dev/video0 \
		--no-display \
		--conn-str rabbitmq;5672;guest